service: gha-dynamodb-local
functions:
  name: "get-user"
  handler: src/main.handler

provider:
  name: aws
  region: "eu-central-1"
  stage: ${opt:stage, 'dev'}
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
custom:
  webpack:
    webpackConfig: webpack.config.ts
    includeModules:
      forceExclude:
        - aws-sdk

package:
  individually: true

plugins:
  - serverless-webpack
