name: CI
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: npm
      - uses: rrainn/dynamodb-action@v2.0.0
        with:
          port: 8000
          cors: "*"
      - run: npm i
      - run: npx jest
